### ISSUE TITLE
Idea: proper logging

### ISSUE THREAD

**Issue by stefanleh** [uklance/gradle-dependency-export#4]
Hi Lance,

id like to introduce proper logging to the plugin:

    logger.info(), logger.lifecycle() ...

The logger is provided by gradle itself, so all whats needed to be added are one-liners.
I suggest logging of:
* used configurations (always logged)
* the configuration currently processed (on info level so you can see them with gradle ... --info)
* copied artifacts and poms (on info level so you can see them with gradle ... --info)

What do you think about it?

**Comment by stefanleh** [comment]
Please see pull request #1 .

**Comment by uklance** [comment]
Please see this commit
https://github.com/uklance/gradle-dependency-export/commit/036344f18a3dd2df5301cc7ffc79051a7f549caa

Where I
1. Put back you canBeResolved = true logic
2. Log the names of the configurations being exported
3. Sort and log the filenames exported at the end of the task
4. Make the configurations property public

If you are happy with these changes, I'll publish a new release

If you're happy with these changes

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by stefanleh** [comment]
Hi Lance, thank you for you changes. I'll rebase my PR on those tomorrow,

**Comment by uklance** [comment]
I've just released version 0.4 to plugin portal as I'm not sure im going to
get to this again for a while
Please give it a whirl when you get a moment

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by stefanleh** [comment]
Thanks for merging.
