### ISSUE TITLE
Idea: include source packages

### ISSUE THREAD

**Issue by stefanleh** [uklance/gradle-dependency-export#6]
Id like to see sources packages for the resolved dependencies included via configuration switch.
This would help if the file based repository the plugin creates get directly used by buildship.
Buildship fetches the source packages for the defined dependencies by default but for this they need to be in the repository.

**Comment by uklance** [comment]
This can be done via an ArtifactResolutionQuery

See
https://stackoverflow.com/questions/39975780/how-can-i-use-gradle-to-download-dependencies-and-their-source-files-and-place-t/39981143#39981143

```
apply plugin: 'java'

repositories { ... }

dependencies {
    compile 'foo:bar:1.0'
    runtime 'foo:baz:1.0'
}

task download {
    inputs.files configurations.runtime
    outputs.dir "${buildDir}/download"
    doLast {
        def componentIds =
configurations.runtime.incoming.resolutionResult.allDependencies.collect {
it.selected.id }
        ArtifactResolutionResult result =
dependencies.createArtifactResolutionQuery()
            .forComponents(componentIds)
            .withArtifacts(JvmLibrary, SourcesArtifact)
            .execute()
        def sourceArtifacts = []
        result.resolvedComponents.each { ComponentArtifactsResult component
->
            Set<ArtifactResult> sources =
component.getArtifacts(SourcesArtifact)
            println "Found ${sources.size()} sources for ${component.id}"
            sources.each { ArtifactResult ar ->
                if (ar instanceof ResolvedArtifactResult) {
                    sourceArtifacts << ar.file
                }
            }
        }

        copy {
            from configurations.runtime
            from sourceArtifacts
            into "${buildDir}/download"
        }
    }
}
```

**Comment by stefanleh** [comment]
Great news! I will build the feature in the coming days based on this information.

**Comment by uklance** [comment]
Great, to get sources and javadoc you'll need to tweak

 .withArtifacts(JvmLibrary, SourcesArtifact)

To

 .withArtifacts(JvmLibrary, SourcesArtifact, JavadocArtifact)

**Comment by stefanleh** [comment]
Sounds good. Will introduce switched for 'withSources' and 'withJavaDoc' then.

**Comment by uklance** [comment]
Perhaps two flags on the task

boolean exportSources
boolean exportJavadoc
